# .github/workflows/tests.yml
name: Run Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      # Check out the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Set up Python
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.9"  # Use the Python version compatible with your project

      # Install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install -e .  # Install the project in editable mode

      # Install Tesseract OCR (required for PDF processing)
      - name: Install Tesseract OCR
        run: |
          sudo apt-get update
          sudo apt-get install -y tesseract-ocr
      
      # Set up environment variables
      - name: Set NLTK data path
        run: |
          mkdir -p $HOME/nltk_data
        shell: bash

      - name: Download NLTK stopwords
        run: |
          python -c "import nltk; nltk.download('stopwords', download_dir='$HOME/nltk_data')"
        env:
          NLTK_DATA: $HOME/nltk_data

      # Create the data/test directory
      - name: Create data/test directory
        run: |
          mkdir -p data/test

      # Run tests
      - name: Run tests
        run: |
          python -m unittest discover tests/
        env:
          NLTK_DATA: $HOME/nltk_data